
default: exetarget

EXE=checkers.exe

LIBS =	\
		-luiconsole \
		-lgame \
		-lplayerplayers \
		-lui \
		-lplayer \
		-lboard \
		-lutil \
		-lboost_program_options \

SUBDIRS =

OBJS =	\
		checkers.o \

LCPPFLAGS=-Wno-unused-local-typedefs

include $(CHECKERS_ROOT)/src/src.mk

