
default: exetarget

EXE=checkers.exe

LIBS =	\
		-luiconsole \
		-lgame \
		-lplayerplayers \
		-lui \
		-lplayer \
		-lboard \
		-lutil \

SUBDIRS =

OBJS =	\
		checkers.o \

include $(CHECKERS_ROOT)/src/src.mk

